# This is a basic workflow to help you get started with Actions

name: Code Checks

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the development branch
  pull_request:
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - uses: Actions-R-Us/actions-tagger@latest
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
        with:
          publish_latest_tag: 'true'

      - name: set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Spotless Check
        run:  ./gradlew spotlessCheck
        continue-on-error: false

      - name: Unit Test
        run:  ./gradlew test
        continue-on-error: true # IMPORTANT: allow pipeline to continue to Android Test Report step

      - name: Android Test Report Action
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}

      - name: ktlint
        uses: ScaCap/action-ktlint@master
        with:
          android: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
